import base64
from Crypto.Cipher import AES
import json
import os
import glob

Ezxx = ("This Script Generated By : EstebanZxx\nBeta Test Module : V1\n=====================================\nResult Decrypt : ")

def decrypt_aes_ecb_128(ciphertext, key):
    cipher = AES.new(key, AES.MODE_ECB)
    plaintext = cipher.decrypt(ciphertext)
    return plaintext.rstrip()

def get_latest_nm_file():
    list_of_files = glob.glob('/sdcard/Download/Nekogram/*.nm') 
    latest_file = max(list_of_files, key=os.path.getctime)
    return latest_file

def main():
    base64_key = "X25ldHN5bmFfbmV0bW9kXw=="
    key = base64.b64decode(base64_key)

    latest_nm_file = get_latest_nm_file()
    with open(latest_nm_file, 'rb') as file: 
        encrypted_text = file.read()
        
    ciphertext = base64.b64decode(encrypted_text)

    decrypted_text = decrypt_aes_ecb_128(ciphertext, key)
    formatted_text = decrypted_text.decode('utf-8').replace("b'", "").rstrip("'")

    with open('/sdcard/Result.txt', 'w') as file:
        file.write(formatted_text)

    print(Ezxx + formatted_text)

if __name__ == "__main__":
    main()
